### ISSUE TITLE
Only Docker install ?

### ISSUE THREAD

**Issue by sachaz** [loomio/loomio-deploy#23]
Hi,

If we are talking about production service, you cannot provide only a Docker installation process.
How do I maintain up to date this Docker black blox other the time ?

Please provide a documentation to explain how to install manualy and packaged versions for various systems.

**Comment by robguthrie** [comment]
We've put quite a lot of work into the Docker approach and that's the only one we're willing to support at this time.

The 'how to update' instructions are within the loomio-deploy/README.md file. 

We're investing more in the Docker approach right now, adding a layer of Terraform for provisioning and then we'll be adding scaling and monitoring.

We also offer managed installs of Loomio as a core part of our business, if you want production Loomio services please get in touch.

**Comment by sachaz** [comment]
Docker is not suitable with our security policy, this is a dev tool for us :)
Again give a process to install out of a container this is the only way to have your product get used by a larger number of users.

**Comment by robguthrie** [comment]
Ok thanks.

**Comment by sachaz** [comment]
You said OK, it means ok we gona to consider this point and provide a real process to install Loomio ?

**Comment by gdpelican** [comment]
@sachaz I can't help but think that your language is a bit incendiary here. We've provided a tool that allows people to easily install our open source software, on any server, for free. It's very similar to the tool that we use to deploy Loomio to production environments to all of our private hosted customers, who are ostensibly happy enough with our production service to pay us monthly for the use of it. It is not, by our professional estimation,  a 'not real' or insecure deployment system.

You're welcome to feel differently. But you're not welcome to make aggressive demands on our time because of those feelings, or enforce that we _need_ to do anything which we've stated we're not intending to do. If you want to deploy Loomio outside of Docker, you will need to figure out how to do it.

That being said, Loomio is a web app, and it's not so different from other web apps that you couldn't get it running with a little elbow grease. Have you [set up a development environment](https://github.com/loomio/loomio/blob/master/docs/en/development_handbook/quickstart.md)? That'd be a really good start.

Here are the composed docker images that we include, so any production server running Loomio will want this set of software installed:
- The Loomio web app
- Letsencrypt (for an SSH cert)
- Nginx (a proxy server)
- Mailin (for reply by email)
- Postgres (the database)
