### ISSUE TITLE
Would like to package this repository for Debian

### ISSUE THREAD

**Issue by Manas-kashyap** [loomio/loomio-deploy#40]
Hi, 
I am Manas Kashyap , an active Debian contributor and i wanted to package this repository in Debian, 
So, i am asking the permission from the developers to do it plus it would be really grateful if you can list the dependencies required by this repository. 
Thanking you

**Comment by robguthrie** [comment]
Replying here because that's the correct thread. I don't feel good about the idea of publishing deb packages. I think there is a huge amount of complexity to running a Loomio stack and this is well managed by the docker-compose based system which we currently support. 

Loomio does not co-exist well with other systems, it's aways best to have a host just for Loomio, giving it all the ports it needs etc.

**Comment by robguthrie** [comment]
If you wish, you may, and I appreciate the efforts - but I cannot make any promises to support you.

**Comment by robguthrie** [comment]
Thanks for bringing this up. We're discussed this topic further here: https://github.com/loomio/loomio/issues/5283
