### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by Barberous** [loomio/loomio-deploy#64]
I am having the following error after installing via loomio deploy.

WARN: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: wrong version number

Could anyone point me in the right direction?

**Comment by frewsxcv** [comment]
I'm seeing the same thing. Did you happen to figure it out @Barberous?

**Comment by Barberous** [comment]
No. Looks to be broken, seen many people complain of the same issue.
Looks like the support is fix it yourself in dev or pay for service.

I had better luck with decidim. https://github.com/Platoniq/decidim-install/blob/master/decidim-bionic.md

**Comment by robguthrie** [comment]
We're a Rails app. We just use the Rails mailer system.  Directly, without any layers of Loomio code. I did not write it and I don't even know how this code works, so any idea that I should be helping you is really misplaced.

I'm not prepared to help you debug Rails libraries - or in fact, just configure your mail server settings correctly (because it probably does not have a bug). It works fine for me and others so you'll need to ask for help with the library maintainers.
