### ISSUE TITLE
Let's Encrypt cert does not cover channels.loomio.example.com

### ISSUE THREAD

**Issue by eternaltyro** [loomio/loomio-deploy#76]
Somehow, there's a new sub-subdomain in the network tab of Firefox that is channels.loomio.example.com. The domain I chose for loomio was loomio.example.com. 

channels.loomio.example.com - does not have a valid certificate (or docker-compose components didn't create for it) and this is cause for potential errors in the page.

**Comment by robguthrie** [comment]
Hi @eternaltyro - Sorry about this, is this a new site or one that you've been running a while?

You need to create a `channels_env` (based on scripts/default_channels_env from this repo) alongside the existing `env` file.

This will trigger a certificate fetch from letsencrypt, however you will need to add a CNAME record for channels.loomio.example.com -> loomio.example.com too

**Comment by eternaltyro** [comment]
> Hi @eternaltyro - Sorry about this, is this a new site or one that you've been running a while?

This is a new site.

> You need to create a `channels_env` (based on scripts/default_channels_env from this repo) alongside the existing `env` file.
> 
> This will trigger a certificate fetch from letsencrypt, however you will need to add a CNAME record for channels.loomio.example.com -> loomio.example.com too

I will try this and report back if there are problems. Thanks for now :+1:

**Comment by eternaltyro** [comment]
@robguthrie once I do the changes, should I restart the stack? Is there a safe way to do it ?

**Comment by eternaltyro** [comment]
I raised a PR for this change to the doc too: https://github.com/loomio/loomio-deploy/pull/77

**Comment by robguthrie** [comment]
Thanks for the PR! 
the restart process just as documented in the readme:
docker-compose down; docker-compose up -d

**Comment by phleba** [comment]
Hello everyone, 

I also experience an issue with the channels. I have set up the channels_env file correctly and added the CNAME DNS records. The weird thing is, that loomio _seems_ to work normal. I can access it, sign in, post, discuss. 
But the web console continuously throws messages like this

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://channels.loomio.domain.tld/socket.io/?channel_token=sometoken&EIO=3&transport=polling&t=NSxwdnO

When I go to channels.loomio.domain via browser, I get a 502 Bad Gateway message.

I don't really understand the purpose of channels and can't find anything in the Handbook. What is it for? Do I need it at all, since it seems to work either way...? Or is Loomio then lacking functionality I don't understand right now?
